### ISSUE TITLE
三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认...

### ISSUE THREAD

**Issue by tx1538** [lan-tianxiang/jd_shell#10]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：
~/jd $ bash jd.sh jd_bean_change
jd.sh: line 38: crontab: command not found
jd.sh: line 39: crontab: command not found
jd.sh: line 290: perl: command not found
jd.sh: line 291: perl: command not found

在/data/data/com.termux/files/home/jd/scripts、/data/data/com.termux/files/home/jd/scripts/backUp、/data/data/com.termux/files/home/jd/config三个目录下均未检测到 jd_bean_change 脚本的存在，请确认...

**Comment by lan-tianxiang** [comment]
第一步第一步，就是依赖那一步肯定有些东西没有安装上，网络良好的情况下，再运行一次那一步

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tx1538 ***@***.***&gt;;
发送时间：2021年3月14日(星期天) 晚上8:28
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台，精确到版本
 
A：
 
3. 按照以下哪个教程做的
  
 Linux
 
 Android
 
 MacOS
 
 Docker
  
4. 详细叙述
 
(1) 具体问题
 
A：
 
(2) 详细日志
 
A：
 
5.软件版本和npm install
 
(1) Node.js版本
 
A：
 
(2) npm版本
 
A：
 
(3)npm install的日志
 
A：
 ~/jd $ bash jd.sh jd_bean_change
 jd.sh: line 38: crontab: command not found
 jd.sh: line 39: crontab: command not found
 jd.sh: line 290: perl: command not found
 jd.sh: line 291: perl: command not found
 
在/data/data/com.termux/files/home/jd/scripts、/data/data/com.termux/files/home/jd/scripts/backUp、/data/data/com.termux/files/home/jd/config三个目录下均未检测到 jd_bean_change 脚本的存在，请确认...

**Comment by tx1538** [comment]
重新卸载安装解决了你这个问题。
但是还有个问题就是定时文件里面内容是不全的，重新卸载更新也是，另外一台手机上也是这样。几个文件夹的同文件都是只有十几行。
![1615800230707](https://user-images.githubusercontent.com/79694451/111131481-4bbfd480-8546-11eb-94ec-4bfebbfaaa8c.jpg)
![Uploading 1615800255599..jpg…]()


#

**Comment by lan-tianxiang** [comment]
我是这样设置的，没错的，大兄弟。 你在运行一下


bash git_pull.sh




就同步所有的定时了，认真看教程

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tx1538 ***@***.***&gt;;
发送时间：2021年3月15日(星期一) 下午5:24
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10)
-----------------------------------

 

 
重新卸载安装解决了你这个问题。
 但是还有个问题就是定时文件里面内容是不全的，重新卸载更新也是，另外一台手机上也是这样。几个文件夹的同文件都是只有十几行。

**Comment by lan-tianxiang** [comment]
可以了吗

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tx1538 ***@***.***&gt;;
发送时间：2021年3月15日(星期一) 下午5:24
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10)
-----------------------------------

 

 
重新卸载安装解决了你这个问题。
 但是还有个问题就是定时文件里面内容是不全的，重新卸载更新也是，另外一台手机上也是这样。几个文件夹的同文件都是只有十几行。

**Comment by tx1538** [comment]
> 可以了吗
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tx1538 ***@***.***&gt;; 发送时间：2021年3月15日(星期一) 下午5:24 收件人："lan-tianxiang/jd_shell" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10) ----------------------------------- 重新卸载安装解决了你这个问题。 但是还有个问题就是定时文件里面内容是不全的，重新卸载更新也是，另外一台手机上也是这样。几个文件夹的同文件都是只有十几行。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.





还是不行。更新以后这两个文件还是不完整。我直接复制了别人的 文件，别人用的另一个哭的是 3.03版本。

**Comment by lan-tianxiang** [comment]
> > 可以了吗
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："tx1538 _**@**_._**>; 发送时间：2021年3月15日(星期一) 下午5:24 收件人："lan-tianxiang/jd_shell" _**@**_.**_>; 抄送："lan-tianxiang _**@**_._**>;"Comment _**@**_.**_>; 主题：Re: [lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10) ----------------------------------- 重新卸载安装解决了你这个问题。 但是还有个问题就是定时文件里面内容是不全的，重新卸载更新也是，另外一台手机上也是这样。几个文件夹的同文件都是只有十几行。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 还是不行。更新以后这两个文件还是不完整。我直接复制了别人的 文件，别人用的另一个哭的是 3.03版本。


感觉一般是网络的问题，因为github某些运营商非常的慢，你可以复制或者截一个  运行git_pull.sh的日记给我看一下

**Comment by tx1538** [comment]
我先把那几个不完全的配置文件删除了。然后运行脚本更新文件，结果如下，然后已删除的那几个文件也更新了，但还是残缺不全，我开了vpn程序，网络应该没问题，两台手机都操作了，也是同样结果。
![1615974623533](https://user-images.githubusercontent.com/79694451/111448401-5e6c1200-86dc-11eb-9d59-49ff12aeabb2.jpg)
![1615974653349](https://user-images.githubusercontent.com/79694451/111448404-5f9d3f00-86dc-11eb-9ee4-5aaad53596db.jpg)
![Uploading 1615974747052..jpg…]()
![Uploading 1615974776402..jpg…]()
![Uploading 1615974794525..jpg…]()
![Uploading 1615974809234..jpg…]()

**Comment by lan-tianxiang** [comment]
确实没有获取完整，&nbsp; git clone的日记里面有个 refuse 0，说明更新脚本失败了。
和git有关，经过我的判断，还是网络问题。
我知道你开了VPN，但是termux里面的git不走VPN，举个最简单的道理，你去ping www.google.com也是不同的，一个道理。


解决方案如下:&nbsp;&nbsp;
很简单，既然你有vpn，那就打开VPN软件看一下代理的端口，开启VPN后，在termux内输入


git config --global http.proxy http://127.0.0.1:你的端口


再运行更新命令或者重头安装都可以






----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tx1538 ***@***.***&gt;;
发送时间：2021年3月17日(星期三) 下午5:54
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 三个目录下均未检测到 jd_bean_sign 脚本的存在，请确认... (#10)
-----------------------------------

 

 
我先把那几个不完全的配置文件删除了。然后运行脚本更新文件，结果如下，然后已删除的那几个文件也更新了，但还是残缺不全，我开了vpn程序，网络应该没问题，两台手机都操作了，也是同样结果。
