### ISSUE TITLE
大佬，安卓和win10都是no such file如何解

### ISSUE THREAD

**Issue by CT0217** [lan-tianxiang/jd_shell#102]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
按照说明安装一路走下来，安装最后显示安装完成，一键脚本显示已完成，电脑几天没开打开就变成了nosuchfile 重新安装还是一样，小米手机也是no such，求大佬百忙之中解答一下疑惑

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
刚上床，哈哈，方便带一下截图吗

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："chen ***@***.***&gt;;
发送时间：2021年6月4日(星期五) 凌晨0:04
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 大佬，安卓和win10都是no such file如何解 (#102)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 按照说明安装一路走下来，安装最后显示安装完成，一键脚本显示已完成，电脑几天没开打开就变成了nosuchfile 重新安装还是一样，小米手机也是no such，求大佬百忙之中解答一下疑惑
 
(2) 详细日志
 
A：

**Comment by CT0217** [comment]
![微信图片_20210604215648](https://user-images.githubusercontent.com/77103305/120813349-62435e00-c580-11eb-9b63-8acefa7dba88.jpg)
![652953b4979a2100daff2aea27bf91a](https://user-images.githubusercontent.com/77103305/120813356-640d2180-c580-11eb-838a-9ea67fda403c.jpg)
![68cc4ee2e99e01fa11e1569dd25148f](https://user-images.githubusercontent.com/77103305/120813359-64a5b800-c580-11eb-9532-5f893f7fce4f.jpg)
满分感谢！麻烦大佬帮忙看看，谢过

**Comment by CT0217** [comment]
win10解决了，，，cd后面少个空格，快哭了
