### ISSUE TITLE
外部扫码接口

### ISSUE THREAD

**Issue by Mashiro2000** [lan-tianxiang/jd_shell#107]
### 想要增加什么样的功能或者哪里存在不足之处呢？
想用扩展自己的服务群众，增加京喜工厂的工人数量，每次邀请其他人使用脚本，一听说扫码就害怕，想用类似以前的代挂网，提供一个外部扫码的接口
![Screenshot_2021-06-06-10-48-35-519_com android browser](https://user-images.githubusercontent.com/40681822/120910866-22e04480-c648-11eb-8396-4179c44e57a9.jpg)
![Screenshot_2021-06-06-10-48-24-014_com android browser](https://user-images.githubusercontent.com/40681822/120910869-25429e80-c648-11eb-8b8a-022755cee998.jpg)

**Comment by lan-tianxiang** [comment]
行的，增加外部接口没问题

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Mashiro2000 ***@***.***&gt;;
发送时间：2021年6月6日(星期天) 上午10:51
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 外部扫码接口 (#107)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
想用扩展自己的服务群众，增加京喜工厂的工人数量，每次邀请其他人使用脚本，一听说扫码就害怕，想用类似以前的代挂网，提供一个外部扫码的接口

**Comment by qingcheng123** [comment]
外不扫码接口怎么使用

**Comment by lan-tianxiang** [comment]
10号之后有时间，到时候加

**Comment by zqh2333** [comment]
弄好了踢我一脚，非常需要这个功能

**Comment by DdQhM** [comment]
> 弄好了踢我一脚，非常需要这个功能

同求踢一脚
