### ISSUE TITLE
lan-tianxiang/jd_shell:latest 获取不到docker image~

### ISSUE THREAD

**Issue by cosmos4343** [lan-tianxiang/jd_shell#11]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lan-tianxiang** [comment]
刚刚测试更新的，还在改，今晚就可以了，抱歉久等了😂&nbsp;


----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："cosmos4343 ***@***.***&gt;;
发送时间：2021年3月20日(星期六) 下午5:11
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] lan-tianxiang/jd_shell:latest 获取不到docker image~ (#11)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台，精确到版本
 
A：
 
3. 按照以下哪个教程做的
  
 Linux
 
 Android
 
 MacOS
 
 Docker
  
4. 详细叙述
 
(1) 具体问题
 
A：
 
(2) 详细日志
 
A：
 
5.软件版本和npm install
 
(1) Node.js版本
 
A：
 
(2) npm版本
 
A：
 
(3)npm install的日志
 
A：

**Comment by lan-tianxiang** [comment]
可以了，直接运行一键安装脚本即可，久等了😂
