### ISSUE TITLE
大家伙的还能用吗

### ISSUE THREAD

**Issue by iskycc** [lan-tianxiang/jd_shell#119]
作者貌似删库了
![image](https://user-images.githubusercontent.com/81439128/121412399-3fa5b080-c997-11eb-85f9-ca32ebd6d5f0.png)
脚本都变成1B了

**Comment by lan-tianxiang** [comment]
已修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："iskycc ***@***.***&gt;;
发送时间：2021年6月10日(星期四) 凌晨2:55
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 大家伙的还能用吗 (#119)
-----------------------------------

 

 
作者貌似删库了
 
 脚本都变成1B了
