### ISSUE TITLE
今天惊喜领红包88，一直卡住不过去，另麻烦看下我这个格式对不对，老是跳不过去这个js

### ISSUE THREAD

**Issue by CT0217** [lan-tianxiang/jd_shell#136]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ x] Yes
- [ ] No

### (1) 具体问题
A：卡在惊喜88红包这里，另外控制面板无法跳过，麻烦大佬看下格式对不对
![微信图片_20210613211607](https://user-images.githubusercontent.com/77103305/121808794-c7880500-cc8c-11eb-8864-98061842410b.jpg)

### (2) 详细日志
A：

**Comment by CT0217** [comment]
![微信图片_20210613232534](https://user-images.githubusercontent.com/77103305/121813455-b942e480-cc9e-11eb-8d70-06fbf43a25ec.jpg)
不知道这个对不对，，，小白求指导。。

**Comment by lan-tianxiang** [comment]
不对的

**Comment by lan-tianxiang** [comment]
```
case $1 in
  jd_jxlhb)
    TempBlockCookie="5"      # 账号5不玩京喜红包
    ;;
esac
```

**Comment by CT0217** [comment]
![IMG_20210614_115130](https://user-images.githubusercontent.com/77103305/121836879-f0e57700-cd06-11eb-8f39-85387c270671.jpg)
这个应该对了吧，老大，麻烦再看下

**Comment by lan-tianxiang** [comment]
嗯，再把地下这个前面加上 ##
![image](https://user-images.githubusercontent.com/42911023/121842625-4aec3980-cd13-11eb-9367-e9ce5ea0e44f.png)

**Comment by CT0217** [comment]
![微信图片_20210614132518](https://user-images.githubusercontent.com/77103305/121842992-ff865b00-cd13-11eb-91ab-b72d702624f8.jpg)
这样子就对了吧。。。问的我都有点不好意思了，如果不对还请劳烦您给个图片，哈哈

**Comment by lan-tianxiang** [comment]
对的，可以手动运行完看看日记成功了没有
