### ISSUE TITLE
ZOO 6-16 8:35 修复部分账号火爆

### ISSUE THREAD

**Issue by lan-tianxiang** [lan-tianxiang/jd_shell#138]

**Comment by Mashiro2000** [comment]
![Uploading Screenshot_2021-06-14-18-51-07-437_com.android.browser.jpg…]()

**Comment by Mashiro2000** [comment]
![Screenshot_2021-06-14-18-51-07-437_com android browser](https://user-images.githubusercontent.com/40681822/121888667-e19e0380-ccdd-11eb-8eac-6d851e6628ff.jpg)
![Uploading Screenshot_2021-06-14-18-51-07-437_com.android.browser.jpg…]()

**Comment by lan-tianxiang** [comment]
@Mashiro2000 再更新一下

**Comment by lan-tianxiang** [comment]
优化满级提示导致不助力问题 6-16 11:18
