### ISSUE TITLE
/home/myid/jd/config/crontab.list 文件不存在，请先定义你自己的crontab.list...

### ISSUE THREAD

**Issue by 13636308814** [lan-tianxiang/jd_shell#14]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：windows 子系统  ubuntu20.04

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：
/home/myid/jd/config/crontab.list 文件不存在，请先定义你自己的crontab.list...

可是实际上config里面的文件已经配置好

### (2) 详细日志
A：

### (1) Node.js版本

A：
10.19.0

### (2) npm版本

A：
6.14.4
### (3)npm install的日志

A：
root@DESKTOP-KUA7M9H:/home/myid/jd/scripts# npm install
audited 207 packages in 2.683s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@DESKTOP-KUA7M9H:/home/myid/jd/scripts#

**Comment by lan-tianxiang** [comment]
是用一键脚本安装的吗，还是通过git clone安装的

**Comment by lan-tianxiang** [comment]
推荐使用首页的一键脚本进行安装

**Comment by lan-tianxiang** [comment]
当然，你已经安装了的话也没关系。
直接运行修复脚本就行了，你设置的COOKIE什么的都不会丢
进入脚本目录，执行
bash repair.sh

**Comment by 13636308814** [comment]
> 是用一键脚本安装的吗，还是通过git clone安装的

原来是gitclon安装的，改成一键安装就好了，解决了
