### ISSUE TITLE
我知道远程访问控制面板要公网IP，但是有没有其他方式能够远程增删COOKIE的方法

### ISSUE THREAD

**Issue by lan-tianxiang** [lan-tianxiang/jd_shell#15]
我知道远程访问控制面板要公网IP，但是有没有其他方式能够远程增删COOKIE的方法

_Originally posted by @donotclickme in https://github.com/lan-tianxiang/jd_shell/discussions/13_

**Comment by lan-tianxiang** [comment]
可以，准备通过阿里云来实时传输账号列表和二维码等操作

**Comment by donotclickme** [comment]
好的大佬------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月28日(星期天) 中午1:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 我知道远程访问控制面板要公网IP，但是有没有其他方式能够远程增删COOKIE的方法 (#15)
