### ISSUE TITLE
可以搭建在服务器上面吗？

### ISSUE THREAD

**Issue by yiyule10** [lan-tianxiang/jd_shell#17]
### 想要增加什么样的功能或者哪里存在不足之处呢？
能不能直接搭建在服务器上面

**Comment by lan-tianxiang** [comment]
完全可以，注意端口安全

**Comment by yiyule10** [comment]
![image](https://user-images.githubusercontent.com/71067732/112832227-99504b80-90c7-11eb-8e71-1fe48dbdac7e.png)
无法输入密码，腾讯云的轻量服务器

**Comment by yiyule10** [comment]
![image](https://user-images.githubusercontent.com/71067732/112835675-2ac1bc80-90cc-11eb-872e-2ccbc73be8bb.png)
无法启用操作面板

**Comment by yiyule10** [comment]
@lan-tianxiang 无法启用操作面板![image](https://user-images.githubusercontent.com/71067732/112835748-475df480-90cc-11eb-8491-7bc627f395be.png)

**Comment by yiyule10** [comment]
@lan-tianxiang 
![image](https://user-images.githubusercontent.com/71067732/112837289-45953080-90ce-11eb-84dc-1345c9751e8d.png)

**Comment by yiyule10** [comment]
@lan-tianxiang 
![image](https://user-images.githubusercontent.com/71067732/112837347-59409700-90ce-11eb-9baf-fa4950710f88.png)
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by lan-tianxiang** [comment]
尝试过运行修复脚本吗 repair.sh

**Comment by lan-tianxiang** [comment]
还有说明一下你的node版本是多少

**Comment by lan-tianxiang** [comment]
大概率和node版本有关，你先用下修复脚本，数据不会丢

**Comment by yiyule10** [comment]
没有运行修复脚本，系统镜像是CentOS7.6
我去运行一下修复脚本，谢谢

**Comment by lan-tianxiang** [comment]
好，你先试试，我用CentOS8测试正常。用修复脚本还是不行的话就肯定是版本问题
你可以输入
`npm install -g n`
来进行升级node版本

**Comment by yiyule10** [comment]
运行完修复脚本，问题解决了，谢谢指点

**Comment by lan-tianxiang** [comment]
好的
