### ISSUE TITLE
获取更新时能不能不重置auth.json

### ISSUE THREAD

**Issue by wulang7726516** [lan-tianxiang/jd_shell#18]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：每次执行git_pull.sh之后总是会重置auth.json，本来已经设置好了用户名密码，只要已更新又变回初始的了，很不方便。

### (2) 详细日志
A：

+----------------- 开 始 执 行 更 新 脚 本 -----------------+

   活动脚本目录：/jd/scripts

   当前系统时间：2021-03-29 19:36

+-----------------------------------------------------------+
1
1
3
更新shell脚本，原地址：https://gitee.com/highdimen/jd_shell

Fetching origin
HEAD is now at 660afab Update README.md

shell脚本更新完成...

--------------------------------------------------------------

更新LXK9301脚本，原地址：https://gitee.com/highdimen/clone_scripts

Fetching origin
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://gitee.com/highdimen/clone_scripts
 + 71529b1...5642b77 master     -> origin/master  (forced update)
HEAD is now at 5642b77 sync

更新shylocks脚本，原地址：https://gitee.com/highdimen/jd_scripts

Fetching origin
HEAD is now at 21b139b Update and rename Sync_JD_Shell_To_Gitee.yml to Sync_JD_Scripts_To_Gitee.yml

控制面板检查&更新完成
检测到未设置密码，用户名：admin，密码：adminadmin

活动脚本更新完成......

**Comment by lan-tianxiang** [comment]
好的，我检查下什么原因

**Comment by lan-tianxiang** [comment]
修复了！！
