### ISSUE TITLE
同时填了Push Plus与Telegram的相关代码，好像由于网络问题卡住了。

### ISSUE THREAD

**Issue by xxp2277** [lan-tianxiang/jd_shell#19]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：旁路由N1通过docker使用一键脚本安装的，然后登录面板编辑config.sh。
同时填了Push Plus与Telegram的相关代码。
export PUSH_PLUS_TOKEN="xxxxxxxxxxxxxxxxxxxxx"

export TG_BOT_TOKEN="xxxxxxxxx"
export TG_USER_ID="xxxxxxxx"
测试使用putty登录N1（作为旁路由，已科学上网）后台，进入docker后，运行bash jd.sh jd_bean_change.js now，日志后半部分如下，然后界面卡住不动。push plus正常收到通知，而tg没有通知。删除tg相关的token和id后完全正常，个人怀疑是docker本身没有科学上网导致无法通过tg发送，今天将项目挂了一天但是登录192.168.x.2:5678后几乎查看不到任何运行日志，估计每个计划任务都有卡在tg发送然后卡住的问题。

尝试在portainer界面将网络从bridge改成host未成功。不知道怎么让docker能正常科学上网。
另外希望能加入功能：设置每个脚本的最长运行时间，否则有耗尽系统资源的可能。

### (2) 详细日志
A：

> 您未提供server酱的SCKEY，取消微信推送消息通知🚫
> 
> push+发送一对一通知消息完成。
> 
> 您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知🚫
> 
> 您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知🚫
> 
> 您未提供企业微信机器人推送所需的QYWX_KEY，取消企业微信推送消息通知🚫
> 
> 您未提供企业微信应用消息推送所需的QYWX_AM，取消企业微信应用消息推送消息通知🚫
> 
> 您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知🚫
> 
然后卡在此界面不动。

**Comment by lan-tianxiang** [comment]
好，建议可接受，安排上行程了

**Comment by lan-tianxiang** [comment]
功能更新上了，自行修改config.sh的参数

**Comment by xxp2277** [comment]
注意休息！
看来程序员都是强迫症，有bug都想修复。哈哈

**Comment by lan-tianxiang** [comment]
哈哈，好
