### ISSUE TITLE
Docker: 定时任务不执行，只能手动执行

### ISSUE THREAD

**Issue by xn408163898** [lan-tianxiang/jd_shell#21]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x ] Docker

## 3. 是否用一键脚本部署的？

- [ x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：
定时任务里面bash jd jd_speed_redpocke 这样写 不会执行，必须改为bash /jd/jd.sh jd_speed_redpocke才会执行定时任务，这是什么原因

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
进入我软件的目录在运行命令，教程的前几行就明确了。
针对你这台机器，先输入
cd jd/
然后再
bash jd.sh xxxxxxx

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xn408163898 ***@***.***&gt;;
发送时间：2021年3月30日(星期二) 上午9:19
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 定时任务不执行，只能手动执行 (#21)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
[x ] 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
[x ] 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
[x ] Docker
  
3. 是否用一键脚本部署的？
  
[ x] Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
[x ] Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 定时任务里面bash jd jd_speed_redpocke 这样写 不会执行，必须改为bash /jd/jd.sh jd_speed_redpocke才会执行定时任务，这是什么原因
 
(2) 详细日志
 
A：

**Comment by xn408163898** [comment]
进入我软件的目录在运行命令，这个我会的，bash jd.sh xxx now这样手动执行脚本也是可以的，但是在crontab.list文件里面的定时任务无法自动执行，必须把文件里面的定时任务格式改为29 7 * * * bash /jd/jd.sh xxx才能正常跑定时任务，你crontab.list文件里面的格式为29 7 * * * bash jd xxx，这应该是个bug吧

**Comment by xn408163898** [comment]
root@jd:/jd $ bash jd.sh xxx now
0000

在/jd/scripts、/jd/scripts/backUp、/jd/config三个目录下均未检测到 xxx 脚本的存在，请确认...

本脚本的用法为：
1. bash jd xxx       # 如果设置了随机延迟并且当时时间不在0-2、30-31、59分内，将随机延迟一定秒数
2. bash jd xxx now   # 无论是否设置了随机延迟，均立即运行
3. bash jd hangup    # 重启挂机程序
4. bash jd panelinit # 开启控制面板
5. bash jd resetpwd  # 重置控制面板用户名和密码

针对用法1、用法2中的"xxx"，无需输入后缀".js"，另外，如果前缀是"jd_"的话前缀也可以省略。
比如：   bash jd.sh jd_bean_change
-----------------------------------------
上面这段描述也有问题，开始说本脚本用法为bash jd xxx，但是是有问题的，实际应该执行bash jd.sh xxx

**Comment by xxp2277** [comment]
昨晚挂了一晚上，进面板看日志，除了5 9 * * * bash /jd/jd.sh jd_bean_change之外，其它好像没发现夜间的运行日志。

**Comment by xn408163898** [comment]
@xxp2277 因为只有第一个定时任务的格式是正确的，其余的都是* * * * * bash jd xxx这种格式，希望作者能够解决吧

**Comment by lan-tianxiang** [comment]
好的，加急了，有时间马上修复 @xn408163898 @xxp2277

**Comment by lan-tianxiang** [comment]
@xxp2277 都是docker吗？

**Comment by xn408163898** [comment]
@lan-tianxiang 我的是docker

**Comment by xxp2277** [comment]
> @xxp2277 都是docker吗？

@lan-tianxiang 是docker。

**Comment by lan-tianxiang** [comment]
修复了这个问题，为了保持docker和linux一键脚本的一致性，请删除容器后重新用一键脚本部署。

**Comment by lan-tianxiang** [comment]
@xn408163898 @xxp2277
