### ISSUE TITLE
JD_DailyBonus出错

### ISSUE THREAD

**Issue by biewenwoshishui021** [lan-tianxiang/jd_shell#22]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ x] No

### (1) 具体问题
A：运行bean_sign，出错，无法签到

### (2) 详细日志
A：

🔔京东多合一签到, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/30/2021, 11:17:16 AM=====================

JD_DailyBonus.js 文件下载异常:TypeError: Cannot convert undefined or null to object

JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

push+发送一对一通知消息完成。

server酱发送通知消息成功🎉

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知🚫

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知🚫

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知🚫

您未提供企业微信机器人推送所需的QYWX_KEY，取消企业微信推送消息通知🚫

您未提供企业微信应用消息推送所需的QYWX_AM，取消企业微信应用消息推送消息通知🚫

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知🚫

🔔京东多合一签到, 结束! 🕛 9.586 秒

**Comment by biewenwoshishui021** [comment]
我用钛备份还原的之前的备份，现在正常了。

**Comment by woaidakele** [comment]
> 我用钛备份还原的之前的备份，现在正常了。

怎么操作的
