### ISSUE TITLE
cookie账号部分丢失

### ISSUE THREAD

**Issue by liaopen123** [lan-tianxiang/jd_shell#25]
## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [ x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ x] No

### (1) 具体问题
A：最近会丢失cookie   我再网页端管理了几个账号，结果进去的时候会丢失几个cookie账号，

### (2) 详细日志
A：
比如web存的有COOKIE1,2,3,4。
过一阵子再登录到客户端页面  就只有cookie1，2，4了。不知道是什么原因。

**Comment by lan-tianxiang** [comment]
刚刚有一个较大的更新，建议重新部署。我先测试一下你说的这个Gug

**Comment by lan-tianxiang** [comment]
请重新部署，问题已解决
