### ISSUE TITLE
虚拟机 Ubuntu18.4 无法运行。

### ISSUE THREAD

**Issue by yege16888** [lan-tianxiang/jd_shell#26]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：Ubuntu18.4 一键脚本 部署后无法使用。 

尝试开启可视化面板 报错：
/home/yg/jd/panel/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/yege/jd/panel/node_modules/got/dist/source/index.js:14:18)
开启失败，请截图并复制错误代码并提交Issues！

尝试使用修复脚本
报错：
/home/yg/jd/update.js:42
function Env(t,e){class s{constructor(t){this.env=t}send(t,e="GET"){t="string"==typeof t?{url:t}:t;let s=this.get;return"POST"===e&&(s=this.post),new Promise((e,i)=>{s.call(this,t,(t,s,r)=>{t?i(t):e(s)})})}get(t){return this.send.call(this.env,t)}post(t){return this.send.call(this.env,t,"POST")}}return new class{constructor(t,e){this.name=t,this.http=new s(this),this.data=null,this.dataFile="box.dat",this.logs=[],this.isMute=!1,this.isNeedRewrite=!1,this.logSeparator="\n",this.startTime=(new Date).getTime(),Object.assign(this,e),this.log("",`\ud83d\udd14${this.name}, \u5f00\u59cb!`)}isNode(){return"undefined"!=typeof module&&!!module.exports}isQuanX(){return"undefined"!=typeof $task}isSurge(){return"undefined"!=typeof $httpClient&&"undefined"==typeof $loon}isLoon(){return"undefined"!=typeof $loon}toObj(t,e=null){try{return JSON.parse(t)}catch{return e}}toStr(t,e=null){try{return JSON.stringify(t)}catch{return e}}getjson(t,e){let s=e;const i=this.getdata(t);if(i)try{s=JSON.parse(th

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

尝试运行任意脚本
报错：
/home/yg/jd/scripts/jx_sign.js:315
function Env(t,e){"undefined"!=typeof process&&JSON.stringify(process.env).indexOf("GITHUB")>-1&&process.exit(0);class s{constructor(t){this.env=t}send(t,e="GET"){t="string"==typeof t?{url:t}:t;let s=this.get;return"POST"===e&&(s=this.post),new Promise((e,i)=>{s.call(this,t,(t,s,r)=>{t?i(t):e(s)})})}get(t){return this.send.call(this.env,t)}post(t){return this.send.call(this.env,t,"POST")}}return new class{constructor(t,e){this.name=t,this.http=new s(this),this.data=null,this.dataFile="box.dat",this.logs=[],this.isMute=!1,this.isNeedRewrite=!1,this.logSeparator="\n",this.startTime=(new Date).getTime(),Object.assign(this,e),this.log("",`🔔${this.name}, 开始!`)}isNode(){return"undefined"!=typeof module&&!!module.exports}isQuanX(){return"undefined"!=typeof $task}isSurge(){return"undefined"!=typeof $httpClient&&"undefined"==typeof $loon}isLoon(){return"undefined"!=typeof $loon}toObj(t,e=null){try{return JSON.parse(t)}catch{return e}}toStr(t,e=null){try{return JSON.stringi

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
收到了，我再看一下

**Comment by lan-tianxiang** [comment]
知道了，node版本太低了，输入
`npm install -g n`
来进行升级node版本

**Comment by yege16888** [comment]
.. 通过其他命令 更新NODE都提示最新版本了
nodejs 已经是最新版 (8.10.0~dfsg-2ubuntu0.4)。
npm 已经是最新版 (3.5.2-0ubuntu4)。

npm install -g n这个指令无法正常运行
提示：
npm WARN checkPermissions Missing write access to /usr/local/lib
/usr/local/lib
└── n@7.1.0 

npm ERR! Linux 5.4.0-70-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "n"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yg/jd/npm-debug.log

**Comment by lan-tianxiang** [comment]
反正就是环境的问题，这个怎么解决我也不好说😂

**Comment by yege16888** [comment]
好吧，我换个版本的Ubuntu再试试吧。

**Comment by lan-tianxiang** [comment]
嗯，不过20肯定可以

**Comment by lan-tianxiang** [comment]
其实，不用换系统，安装docker，然后运行docker的安装脚本也行

**Comment by lan-tianxiang** [comment]
如果系统里面比较多资料，软件啥的

**Comment by yege16888** [comment]
好的 谢谢，已经安装到 VPS上了。
本地虚拟机 不能24小时开着存在局限性。还是VPS安逸。

可视化界面中的Share Code显示 感觉直接调用export_sharecodes.sh 脚本生成log比较直接方便。

**Comment by lan-tianxiang** [comment]
哈哈，的确。不过现在已经不用export_sharecodes.sh，能自动助力了

**Comment by lan-tianxiang** [comment]
在config里面开启AutoHelpme功能就可以了

**Comment by lan-tianxiang** [comment]
前天晚上更新的功能

**Comment by yege16888** [comment]
好的 感谢。
