### ISSUE TITLE
docker的log和config文件夹为空

### ISSUE THREAD

**Issue by xn408163898** [lan-tianxiang/jd_shell#27]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
我是今早提issue的那个人，刚才把docker按照要求重新部署后，发言一个问题，就是本地绝对路径下的log和config文件夹内容为空，而且本地root目录也是空的，我用过linux版本，他是把log和config文件夹生成在root目录下，但是docker版本目录却不见了。这个新版本的定时任务已经可以正常运行，还望修复下这个文件目录的问题

### (2) 详细日志
A：

**Comment by xn408163898** [comment]
刚看了下，脚本的运行log文件，我在docker容器内找到了，以前都是映射到本地的，这应该也是一个bug

**Comment by lan-tianxiang** [comment]
好

**Comment by lan-tianxiang** [comment]
忘了改参数了，已修复！

**Comment by lan-tianxiang** [comment]
麻烦重新部署

**Comment by xn408163898** [comment]
多谢作者，以后更新V4版本，算我一个，多谢啦 哈哈哈

**Comment by lan-tianxiang** [comment]
haha
