### ISSUE TITLE
面板无法开启

### ISSUE THREAD

**Issue by cuxevip** [lan-tianxiang/jd_shell#29]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
面板无法开启
系统Cent0S-7
### (2) 详细日志
A：
[root@instance-8888-1 jd]# bash jd.sh panelinit
记得开启前先认真看Wiki中，功能页里关于控制面板的事项

/root/jd/panel/server.js:75
async function step1() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
开启失败，请截图并复制错误代码并提交Issues！

![IMG_20210330_192403](https://user-images.githubusercontent.com/30213648/113000628-94ac9580-91a2-11eb-9109-7fbec01c7d0d.jpg)
![IMG_20210330_213851](https://user-images.githubusercontent.com/30213648/113000684-a55d0b80-91a2-11eb-816c-720acf0ab0cd.jpg)

**Comment by lan-tianxiang** [comment]
看起来，和这位老哥一样的https://github.com/lan-tianxiang/jd_shell/issues/17
不过尝试过修复脚本还是不行，有没有试过升级node的命令呢

**Comment by lan-tianxiang** [comment]
npm install -g n

**Comment by lan-tianxiang** [comment]
如果还是不行，我也很难说该怎么解决了。
那样的话，推荐换成Centos8。
或者，不用换系统，安装docker，然后运行docker的安装脚本也行

**Comment by lan-tianxiang** [comment]
docker在linux上不怎么消耗资源，可以放心

**Comment by cuxevip** [comment]
> npm install -gn

升级过了，还是这样提示😭
容器没有一建，我不会搭建😂

**Comment by lan-tianxiang** [comment]
容器不用会搭建，安装完用脚本就行呀

**Comment by cuxevip** [comment]
> 容器不用会建造，安装完用脚本就行呀

Last login: Tue Mar 30 21:57:58 2021 from 14.150.4.61
[root@instance-8888-1 ~]# npm install -gn
npm ERR! addLocal Could not install /root
npm ERR! Linux 3.10.0-1160.15.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-gn"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
[root@instance-8888-1 ~]# npm install -g n
/usr/bin/n -> /usr/lib/node_modules/n/bin/n
/usr/lib
└── n@7.1.0
老哥，看下是不是出错了？npm ERR!

**Comment by lan-tianxiang** [comment]
嗯，就是npm的问题

**Comment by lan-tianxiang** [comment]
Ubuntu、Centos安装docker: 
`curl -sSL https://get.daocloud.io/docker | sh`

**Comment by lan-tianxiang** [comment]
不然的话，只能换系统，这个npm的bug我没有研究过

**Comment by cuxevip** [comment]
> 不然的话，只能换系统，这个npm的bug我没有研究过

😂，那我尝一下吧
