### ISSUE TITLE
OpenWRT 的wiki找不到了

### ISSUE THREAD

**Issue by justincnn** [lan-tianxiang/jd_shell#3]
作者你好，wiki里面只有linux的教程，openwrt的找不到了，可以帮忙补充下么？谢谢啊

**Comment by lan-tianxiang** [comment]
好

**Comment by lan-tianxiang** [comment]
你安装docker    走docker的安装路线看下

**Comment by justincnn** [comment]
> 你安装docker 走docker的安装路线看下

我的路由器太弱，没装docker ce，：（
记得以前有个单独的openwrt教程，现在就是找不到了，作者你如果还有的话，还请分享，谢谢啊

**Comment by lan-tianxiang** [comment]
这么久了，不知道你现在还有没有继续尝试用Openwrt来运行😂，我也只能找到这个部分
![image](https://user-images.githubusercontent.com/42911023/112741216-2a370200-8fb6-11eb-9ef2-11f090883278.png)
希望对你有帮助

**Comment by lan-tianxiang** [comment]
其他的部分，若软件包安装成功了，其他跟着Linux的教程来就行了
