### ISSUE TITLE
面板自动后台常驻

### ISSUE THREAD

**Issue by happy-peter** [lan-tianxiang/jd_shell#31]
### 想要增加什么样的功能或者哪里存在不足之处呢？

能否做出ipk模式，长期后台常驻，跟netdata一样，直接ip：5678进面板，不用每次都手动输命令行开启面板，谢谢

**Comment by lan-tianxiang** [comment]
这个没问题，我配置一个参数，后台常驻选项

**Comment by lan-tianxiang** [comment]
输入指令之后，只要不重启和自己手动关，都会在后台运行
