### ISSUE TITLE
有个云主机,装了ubuntu,能不能通过公网ip:5678 进入控制面板

### ISSUE THREAD

**Issue by 13636308814** [lan-tianxiang/jd_shell#33]

**Comment by 13636308814** [comment]
已经按照liunx教程按照, 公网ip:5678无法进入

**Comment by lan-tianxiang** [comment]
您好，ubuntu有没有放行端口呢

**Comment by lan-tianxiang** [comment]
sudo ufw allow 5678

**Comment by 13636308814** [comment]
![image](https://user-images.githubusercontent.com/26049566/113132907-a4cf7e00-9251-11eb-80aa-3a8a92c49dc3.png)

![image](https://user-images.githubusercontent.com/26049566/113132933-af8a1300-9251-11eb-83b2-18df1ebb4be0.png)
![image](https://user-images.githubusercontent.com/26049566/113132990-c3ce1000-9251-11eb-9830-783f476390bc.png)
老大,我试了,还是不行

**Comment by lan-tianxiang** [comment]
ip信息不要暴露，我把问题删了，你私我

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："13636308814 ***@***.***&gt;;
发送时间：2021年3月31日(星期三) 晚上6:49
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 有个云主机,装了ubuntu,能不能通过公网ip:5678 进入控制面板 (#33)
-----------------------------------

 

 

 

 
 老大,我试了,还是不行

**Comment by lan-tianxiang** [comment]
我把你上面的回复删除了

**Comment by lan-tianxiang** [comment]
你留一个方式

**Comment by 13636308814** [comment]
老大,我把云主机账号密码发你,你帮我看看怎么样?





 Aisijem 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lan-tianxiang/jd_shell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 有个云主机,装了ubuntu,能不能通过公网ip:5678 进入控制面板 (#33)





 
我把你上面的回复删除了

**Comment by lan-tianxiang** [comment]
可以，信得过我也行

**Comment by lan-tianxiang** [comment]
qq 你留一个

**Comment by lan-tianxiang** [comment]
我看到了就删

**Comment by 13636308814** [comment]
qq:498733376





 Aisijem 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lan-tianxiang/jd_shell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 有个云主机,装了ubuntu,能不能通过公网ip:5678 进入控制面板 (#33)





 
我看到了就删

**Comment by lan-tianxiang** [comment]
好的

**Comment by 13636308814** [comment]
106.14.123.2&nbsp; &nbsp;


root
33691159zpj.



 Aisijem 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lan-tianxiang/jd_shell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上7:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 有个云主机,装了ubuntu,能不能通过公网ip:5678 进入控制面板 (#33)





 
好的

**Comment by xxp2277** [comment]
账户密码出来了，赶紧删除或者之后改了
