### ISSUE TITLE
依赖安装后，没有找到文档所示的项目路径

### ISSUE THREAD

**Issue by crane168** [lan-tianxiang/jd_shell#36]
![jd-shell](https://user-images.githubusercontent.com/26795319/113232233-4e088980-92cf-11eb-9995-2f16f7308771.png)

**Comment by lan-tianxiang** [comment]
不是这样的，按任意键开始部署，这还没开始部署呢，你就退出了😂

**Comment by lan-tianxiang** [comment]
![image](https://user-images.githubusercontent.com/42911023/113232498-c8d1a480-92cf-11eb-8959-aee0ae257c9a.png)

好兄弟

**Comment by crane168** [comment]
> ![image](https://user-images.githubusercontent.com/42911023/113232498-c8d1a480-92cf-11eb-8959-aee0ae257c9a.png)
> 
> 好兄弟

![4001617254886_ pic_hd](https://user-images.githubusercontent.com/26795319/113247712-2248cc00-92ee-11eb-9e6b-26d69890461b.jpg)
安装脚本跑这个superman去拉了，没有找到，还有有交流群没，在md没找到啊

**Comment by lan-tianxiang** [comment]
知道原因了，你这个机器之前部署过Freefuck的脚本吧

**Comment by lan-tianxiang** [comment]
他的脚本部署的时候，写了一些参数到你的系统里面了

**Comment by lan-tianxiang** [comment]
你用编辑器打开 /etc/profile 这个文件，然后划到最后一行，把关于京东、JD的东西都删除了，重启就可以了。记住按流程走！！！

**Comment by lan-tianxiang** [comment]
交流群仔细找找，表面上肯定没有

**Comment by lan-tianxiang** [comment]
> 你用编辑器打开 /etc/profile 这个文件，然后划到最后一行，把关于京东、JD的东西都删除了，重启就可以了。记住按流程走！！！

`vim /etc/profile`或者`nano /etc/profile`

**Comment by crane168** [comment]
> 知道原因了，你这个机器之前部署过Freefuck的脚本吧

要的就是你这句话，以前跑得superman的

**Comment by lan-tianxiang** [comment]
怎么样，解决了吗

**Comment by lan-tianxiang** [comment]
改完之后重启一下就不会出错了

**Comment by crane168** [comment]
> 改完之后重启一下就不会出错了

666，OK

**Comment by lan-tianxiang** [comment]
好👌🏻&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："crane168 ***@***.***&gt;;
发送时间：2021年4月1日(星期四) 下午5:11
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 依赖安装后，没有找到文档所示的项目路径 (#36)
-----------------------------------

 

  
改完之后重启一下就不会出错了
  
666，OK
