### ISSUE TITLE
关于配置面板里的配置版本

### ISSUE THREAD

**Issue by ryan016** [lan-tianxiang/jd_shell#39]
登录控制面板后，通过对比工具看到的是

```
## Version: v3.7.1
## Date: 2021-03-29
## Update Content: 补充注释，无参数变动
```
而最新版的应该是
```
## Version: v4.1.0
## Date: 2021-03-29
## Update Content: 重新修改AutoHelpOther的功能，启动AutoHelpOther后，将直接导入jcode最新日志来进行互助，jcode日志中含有的互助信息（包括MyXxx和ForOtherXxx）均不用在 config.sh 中填写（填写了也无效）。

## ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 第一区域：jd_scripts特有变量填写区域（需要shell转换的） ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

```

是不是我要手动更新还是怎么的？

**Comment by lan-tianxiang** [comment]
不用，和我不一样软件。

**Comment by lan-tianxiang** [comment]
> 登录控制面板后，通过对比工具看到的是
> 
> ```
> ## Version: v3.7.1
> ## Date: 2021-03-29
> ## Update Content: 补充注释，无参数变动
> ```
> 
> 而最新版的应该是
> 
> ```
> ## Version: v4.1.0
> ## Date: 2021-03-29
> ## Update Content: 重新修改AutoHelpOther的功能，启动AutoHelpOther后，将直接导入jcode最新日志来进行互助，jcode日志中含有的互助信息（包括MyXxx和ForOtherXxx）均不用在 config.sh 中填写（填写了也无效）。
> 
> ## ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 第一区域：jd_scripts特有变量填写区域（需要shell转换的） ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
> ```
> 
> 是不是我要手动更新还是怎么的？

这个应该不是我的配置文件吧

**Comment by lan-tianxiang** [comment]
不一样的复制进入，软件会异常的

**Comment by lan-tianxiang** [comment]
你的那一版目前最新的应该也是这个
## Version: v4.2.1
## Date: 2021-03-31

**Comment by ryan016** [comment]
晓得了，谢谢！

**Comment by lan-tianxiang** [comment]
嗯，不用谢
