### ISSUE TITLE
docker无法克隆镜像

### ISSUE THREAD

**Issue by mingsijie** [lan-tianxiang/jd_shell#4]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos8 arm64

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：docker仓库无法克隆了，请问是否删除了仓库或转移了地址。

### (2) 详细日志
A：
Pulling jd1 (evinedeng/jd:)...
Trying to pull repository docker.io/evinedeng/jd ...
ERROR: repository docker.io/evinedeng/jd not found: does not exist or no pull access

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lan-tianxiang** [comment]
是的，我现在在修改，目前Linux和Android正常且保持更新

**Comment by lan-tianxiang** [comment]
暂时可以用 Dockerfile 在本地生成，dockerhub还没上传

**Comment by mingsijie** [comment]
收到。已自行构建。
