### ISSUE TITLE
你好，crontab里面有自定义的定时任务，这个每次更新会被覆盖丢失，如何更新不丢失已经存在的其他任务呢

### ISSUE THREAD

**Issue by fakers777** [lan-tianxiang/jd_shell#41]
### 想要增加什么样的功能或者哪里存在不足之处呢？
1.希望自定义任务不要丢失，比如有个刷步数的任务，不想搞复杂，每次运行一下脚本就可以了，但和这个定时任务会冲突。请考虑，谢谢
2.能界面增加定时任务，不用自己写定时任务语法，可以吗，类似于BT面板的自定义

**Comment by lan-tianxiang** [comment]
好的，都没问题

**Comment by lan-tianxiang** [comment]
我解释一下你标题里面提到的这个部分。你的脚本只要不以`jd_`开头的，放在定时任务里面就不会被清除

**Comment by fakers777** [comment]
是吗 我再试试，今天好像丢了

**Comment by lan-tianxiang** [comment]
嗯，好。

**Comment by fakers777** [comment]
好像会覆盖啊，我直接编辑的crontab -e 然后保存后，过一段时间再看 任务没有了
我写的是 31 8 * * * bash python3 XXX.py (脚本路径)

**Comment by lan-tianxiang** [comment]
> 好像会覆盖啊，我直接编辑的crontab -e 然后保存后，过一段时间再看 任务没有了
> 我写的是 31 8 * * * bash python3 XXX.py (脚本路径)

原来是这样，懂了。
是这样的，Linux里面的的定时任务，你要写在config底下的crontab.list里面哦
你打开控制面板，在里面编辑完之后保存也是可以的哦

**Comment by lan-tianxiang** [comment]
直接编辑会被先前的覆盖，这点没有错
