### ISSUE TITLE
定时里面的任务重复添加

### ISSUE THREAD

**Issue by baiye233** [lan-tianxiang/jd_shell#46]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：新的容器，更新脚本之后，定时任务里的任务重复添加

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
赶紧拿出日记给我看一下

**Comment by lan-tianxiang** [comment]
要是这个问题真的存在，应该很多人反馈。不过我会先试一下。

**Comment by baiye233** [comment]
+----------------- 开 始 执 行 更 新 脚 本 -----------------+

   活动脚本目录：/root/jd/scripts

   当前系统时间：2021-04-02 20:55

+-----------------------------------------------------------+
1
1
3
更新shell脚本，原地址：https://gitee.com/highdimen/jd_shell

Fetching origin
HEAD is now at fc43e45 Update Sync_JD_Shell_A1_From_Gitee.yml

shell脚本更新完成...

--------------------------------------------------------------

更新LXK9301脚本，原地址：https://gitee.com/highdimen/clone_scripts

Fetching origin
HEAD is now at e44e144 update

更新shylocks脚本，原地址：https://gitee.com/highdimen/jd_scripts

Fetching origin
HEAD is now at 196d1e1 Create jd_bean_change.js

控制面板检查&更新完成
活动脚本更新完成......

脚本目录：/root/jd

**Comment by lan-tianxiang** [comment]
这里反馈显示正常，把定时文件的也给我看看

**Comment by baiye233** [comment]
5 9 * * * bash /root/jd/jd.sh jd_bean_change
23 4 * * * bash /root/jd/jd.sh jd_bean_home
4 0,9 * * * bash /root/jd/jd.sh jd_bean_sign
###41 7,12,19 * * * bash /root/jd/jd.sh jd_beauty
0,30 0 * * * bash /root/jd/jd.sh jd_blueCoin
38 8,12,18 * * * bash /root/jd/jd.sh jd_bookshop
0 0 * * * bash /root/jd/jd.sh jd_car
0 0 * * * bash /root/jd/jd.sh jd_car_exchange
0 0-18/6,19-23/1 * * * bash /root/jd/jd.sh jd_carnivalcity
10 */4 * * * bash /root/jd/jd.sh jd_cash
5 */2 * * * bash /root/jd/jd.sh jd_cfd
6 0,23 * * * bash /root/jd/jd.sh jd_club_lottery
30 7,23 * * * bash /root/jd/jd.sh jd_crazy_joy
10 12 * * * bash /root/jd/jd.sh jd_crazy_joy_bonus
28 * * * * bash /root/jd/jd.sh jd_daily_egg
#20 9 * * 6 bash /root/jd/jd.sh jd_delCoupon
50 * * * * bash /root/jd/jd.sh jd_dreamFactory
10 6,7 * * * bash /root/jd/jd.sh jd_family
15 6-18/6 * * * bash /root/jd/jd.sh jd_fruit
23 7 * * * bash /root/jd/jd.sh jd_get_share_code
26 * * * * bash /root/jd/jd.sh jd_jdfactory
6 0,11 * * * bash /root/jd/jd.sh jd_jdzz
45 */2,23 * * * bash /root/jd/jd.sh jd_joy
35 */1 * * * bash /root/jd/jd.sh jd_joy_feedPets
0 0-16/8 * * * bash /root/jd/jd.sh jd_joy_reward
10 13-20/1 * * * bash /root/jd/jd.sh jd_joy_run
13 8,16,20 * * * bash /root/jd/jd.sh jd_jxd
30 9,12,18 * * * bash /root/jd/jd.sh jd_jxnc
47 1 * * * bash /root/jd/jd.sh jd_kd
30-50/5 12,23 * * * bash /root/jd/jd.sh jd_live
0,30,31 20-23/1 * * * bash /root/jd/jd.sh jd_live_redrain
31 0,12,23 * * * bash /root/jd/jd.sh jd_lotteryMachine
10 0,1-23/4 * * * bash /root/jd/jd.sh jd_mohe
23 */2 * * * bash /root/jd/jd.sh jd_moneyTree
10 6 * * * bash /root/jd/jd.sh jd_ms
40 0,20 * * * bash /root/jd/jd.sh jd_necklace
35 1,23 * * * bash /root/jd/jd.sh jd_nzmh
35 6-18/6 * * * bash /root/jd/jd.sh jd_pet
#25 * * * * bash /root/jd/jd.sh jd_pigPet
10 7-22/1 * * * bash /root/jd/jd.sh jd_plantBean
#41 0,23 * * * bash /root/jd/jd.sh jd_price
21 9 * * * bash /root/jd/jd.sh jd_rankingList
12 1,21,23 * * * bash /root/jd/jd.sh jd_redPacket
47 8 * * * bash /root/jd/jd.sh jd_sgmh
6 0 * * * bash /root/jd/jd.sh jd_shop
46 6,23 * * * bash /root/jd/jd.sh jd_small_home
28 */3 * * * bash /root/jd/jd.sh jd_speed
45 0,23 * * * bash /root/jd/jd.sh jd_speed_redpocke
21 1,6 * * * bash /root/jd/jd.sh jd_speed_sign
31 0,1-23/2 * * * bash /root/jd/jd.sh jd_superMarket
12 8,18 * * * bash /root/jd/jd.sh jd_syj
45 23 * * * bash /root/jd/jd.sh jd_unsubscribe
29 7 * * * bash /root/jd/jd.sh jx_sign
23 4 * * * bash /root/jd/jd.sh jd_bean_home
4 0,9 * * * bash /root/jd/jd.sh jd_bean_sign
###41 7,12,19 * * * bash /root/jd/jd.sh jd_beauty
0,30 0 * * * bash /root/jd/jd.sh jd_blueCoin
38 8,12,18 * * * bash /root/jd/jd.sh jd_bookshop
0 0 * * * bash /root/jd/jd.sh jd_car
0 0 * * * bash /root/jd/jd.sh jd_car_exchange
0 0-18/6,19-23/1 * * * bash /root/jd/jd.sh jd_carnivalcity
10 */4 * * * bash /root/jd/jd.sh jd_cash
5 */2 * * * bash /root/jd/jd.sh jd_cfd
6 0,23 * * * bash /root/jd/jd.sh jd_club_lottery
30 7,23 * * * bash /root/jd/jd.sh jd_crazy_joy
10 12 * * * bash /root/jd/jd.sh jd_crazy_joy_bonus
28 * * * * bash /root/jd/jd.sh jd_daily_egg
#20 9 * * 6 bash /root/jd/jd.sh jd_delCoupon
50 * * * * bash /root/jd/jd.sh jd_dreamFactory
10 6,7 * * * bash /root/jd/jd.sh jd_family
15 6-18/6 * * * bash /root/jd/jd.sh jd_fruit
23 7 * * * bash /root/jd/jd.sh jd_get_share_code
26 * * * * bash /root/jd/jd.sh jd_jdfactory
6 0,11 * * * bash /root/jd/jd.sh jd_jdzz
45 */2,23 * * * bash /root/jd/jd.sh jd_joy
35 */1 * * * bash /root/jd/jd.sh jd_joy_feedPets
0 0-16/8 * * * bash /root/jd/jd.sh jd_joy_reward
10 13-20/1 * * * bash /root/jd/jd.sh jd_joy_run
13 8,16,20 * * * bash /root/jd/jd.sh jd_jxd
30 9,12,18 * * * bash /root/jd/jd.sh jd_jxnc
47 1 * * * bash /root/jd/jd.sh jd_kd
30-50/5 12,23 * * * bash /root/jd/jd.sh jd_live
0,30,31 20-23/1 * * * bash /root/jd/jd.sh jd_live_redrain
31 0,12,23 * * * bash /root/jd/jd.sh jd_lotteryMachine
10 0,1-23/4 * * * bash /root/jd/jd.sh jd_mohe
23 */2 * * * bash /root/jd/jd.sh jd_moneyTree
10 6 * * * bash /root/jd/jd.sh jd_ms
40 0,20 * * * bash /root/jd/jd.sh jd_necklace
35 1,23 * * * bash /root/jd/jd.sh jd_nzmh
35 6-18/6 * * * bash /root/jd/jd.sh jd_pet
#25 * * * * bash /root/jd/jd.sh jd_pigPet
10 7-22/1 * * * bash /root/jd/jd.sh jd_plantBean
#41 0,23 * * * bash /root/jd/jd.sh jd_price
21 9 * * * bash /root/jd/jd.sh jd_rankingList
12 1,21,23 * * * bash /root/jd/jd.sh jd_redPacket
47 8 * * * bash /root/jd/jd.sh jd_sgmh
6 0 * * * bash /root/jd/jd.sh jd_shop
46 6,23 * * * bash /root/jd/jd.sh jd_small_home
28 */3 * * * bash /root/jd/jd.sh jd_speed
45 0,23 * * * bash /root/jd/jd.sh jd_speed_redpocke
21 1,6 * * * bash /root/jd/jd.sh jd_speed_sign
31 0,1-23/2 * * * bash /root/jd/jd.sh jd_superMarket
12 8,18 * * * bash /root/jd/jd.sh jd_syj
45 23 * * * bash /root/jd/jd.sh jd_unsubscribe
29 7 * * * bash /root/jd/jd.sh jx_sign

**Comment by baiye233** [comment]
在脚本运行的日志里，同一个时间也有2个日志

**Comment by lan-tianxiang** [comment]
哇靠，怎么回事

**Comment by lan-tianxiang** [comment]
好

**Comment by lan-tianxiang** [comment]
我反复测试搞了一个小时，都没有出现这种情况。问了一下别人也挺正常的，你要是不介意的话，可以重装看看。

**Comment by baiye233** [comment]
我直接把重复的删除了，再运行就不会出现重复添加定时的情况。就新建容器的时候，第一次手动拉取脚本会重复添加

**Comment by lan-tianxiang** [comment]
好，那就好，有时间我会重新看一下怎么导致的问题

**Comment by baiye233** [comment]
大佬有电报群吗

**Comment by baiye233** [comment]
能加一下你的电报群吗

**Comment by lan-tianxiang** [comment]
> 能加一下你的电报群吗

哈哈，原来刚刚就是你呀，有问题欢迎提问。

**Comment by baiye233** [comment]
好的，哈哈
