### ISSUE TITLE
你这是为啥跟樱花这么像

### ISSUE THREAD

**Issue by zzw2016** [lan-tianxiang/jd_shell#47]

**Comment by lan-tianxiang** [comment]
我可能不太了解，能问一下樱花是什么吗？

**Comment by lan-tianxiang** [comment]
花我知道，是其他软件吗，还是？

**Comment by zzw2016** [comment]
不是,是一个作者的面板是樱花

**Comment by lan-tianxiang** [comment]
方便给我他的github让我看看吗😂，到底看看到底有多像

**Comment by lan-tianxiang** [comment]
还有与他的面板是功能像还是外观像🥺

**Comment by zzw2016** [comment]
跑路了删库了哈哈哈

**Comment by lan-tianxiang** [comment]
好吧😂

**Comment by lan-tianxiang** [comment]
感觉不久我也要跑路了，这几天人一下子多起来

**Comment by lan-tianxiang** [comment]
本来小众的东西

**Comment by zzw2016** [comment]
樱花那个作者是偷ck被举报了,你这个面板可以说跟他一样一样的

**Comment by lan-tianxiang** [comment]
是这样的啊，难怪你担心，不过我的代码都是开源的，可以进行审查。有任何错误的地方你可以指出，包括bug啥的，我都会接受的，哈哈哈

**Comment by zzw2016** [comment]
你看看樱花的   https://img.yzuz.net/image/606736749f532.jpg

**Comment by lan-tianxiang** [comment]
能的话，也可以帮忙看看有没有恶意代码，我也挺担心的，不然我到时得挨骂了

**Comment by lan-tianxiang** [comment]
> 你看看樱花的 https://img.yzuz.net/image/606736749f532.jpg

好的

**Comment by zzw2016** [comment]
刚开始一看到就吓我一跳所以问了这个樱花

**Comment by lan-tianxiang** [comment]
哦，我懂了，樱花你是指的原来FreeFuck的项目吗

**Comment by zzw2016** [comment]
> 哦，我懂了，樱花你是指的原来FreeFuck的项目吗

对

**Comment by lan-tianxiang** [comment]
目前新增的代码功能啥的（不包括面板）几乎都是我自己写的。但是部分面板的代码是参考freefuck的项目的，我更新的时候也写了。  是他的面板有问题吗

**Comment by lan-tianxiang** [comment]
那我得好好重新一行一行的看下了

**Comment by lan-tianxiang** [comment]
细思恐极

**Comment by lan-tianxiang** [comment]
😨

**Comment by zzw2016** [comment]
> 目前新增的代码功能啥的（不包括面板）几乎都是我自己写的。但是部分面板的代码是参考freefuck的项目的，我更新的时候也写了。 是他的面板有问题吗

就是他的代码会上传ck才会被一堆人举报,后来被lx删除秘钥

**Comment by lan-tianxiang** [comment]
关键我不知道有这么一回事

**Comment by lan-tianxiang** [comment]
有相关的链接吗，指的是面板上传ck

**Comment by lan-tianxiang** [comment]
SHELL的部分我能保证没问题

**Comment by lan-tianxiang** [comment]
谢谢你提供这个信息给我，我明天开始重新审查一下面板的代码，有问题我就暂时先换回前一个版本的

**Comment by zzw2016** [comment]
没连接了,

**Comment by lan-tianxiang** [comment]
没事，我自己看也行

**Comment by lan-tianxiang** [comment]
就是能有具体的地方的话，我能更好解决问题

**Comment by zzw2016** [comment]
嗯嗯,你这个库知道的还不是太多,别因为面板一堆人来认为你是樱花直接举报你

**Comment by tjustephen** [comment]
这面板也不是樱花做的，樱花也是用的别人代码。

**Comment by lan-tianxiang** [comment]
是，这个我知道

> 这面板也不是樱花做的，樱花也是用的别人代码。

**Comment by zzw2016** [comment]
> 这面板也不是樱花做的，樱花也是用的别人代码。
可以考虑v4了.都提高门款了,为的就是不让人接单

**Comment by lan-tianxiang** [comment]
程序员其实都是这样，能调用的，只要性能不下降多，都会考虑调用

**Comment by zzw2016** [comment]
作者你可以建一个tg群,方便讨论

**Comment by lan-tianxiang** [comment]
> > 这面板也不是樱花做的，樱花也是用的别人代码。
> > 可以考虑v4了.都提高门款了,为的就是不让人接单

目前在写了，不过就是为了乐趣，搞搞豆。没想着接单什么的

**Comment by lan-tianxiang** [comment]
> 作者你可以建一个tg群,方便讨论

有，只是在Readme里面，很多人找不到罢了

**Comment by lan-tianxiang** [comment]
> > 这面板也不是樱花做的，樱花也是用的别人代码。
> > 可以考虑v4了.都提高门款了,为的就是不让人接单

以后我加强一下这方面的

**Comment by lan-tianxiang** [comment]
一定杜绝这类安全事件

**Comment by lan-tianxiang** [comment]
> 嗯嗯,你这个库知道的还不是太多,别因为面板一堆人来认为你是樱花直接举报你

好

**Comment by zzw2016** [comment]
> > 作者你可以建一个tg群,方便讨论
> 
> 有，只是在Readme里面，很多人找不到罢了

我没找到tg邀请链接

**Comment by lan-tianxiang** [comment]
打开编辑，再回到那个区域试试？

**Comment by baiye233** [comment]
还是找不到

**Comment by lan-tianxiang** [comment]
> 还是找不到

进入首页的编辑模式，搜索小彩蛋
