### ISSUE TITLE
docker 保存config.sh不是立即生效

### ISSUE THREAD

**Issue by 648839699** [lan-tianxiang/jd_shell#49]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [X] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：我的群晖docker  从控制面板中修改config.sh参数保存后，显示保存成功，但不是立即生效，实际运行还是按未保存之前的，不知道要过多久才会按照新保存的。重启容器后就行，是我设置的问题，还是什么情况

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
是这样的，你开启了自动助力对吧，开启之后，修改配置文件，要运行一下bash git_pull.sh
也就是更新一下就去去除缓存。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："648839699 ***@***.***&gt;;
发送时间：2021年4月4日(星期天) 上午7:27
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] docker 保存config.sh不是立即生效 (#49)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：我的群晖docker  从控制面板中修改config.sh参数保存后，显示保存成功，但不是立即生效，实际运行还是按未保存之前的，不知道要过多久才会按照新保存的。重启容器后就行，是我设置的问题，还是什么情况
 
(2) 详细日志
 
A：
