### ISSUE TITLE
无法pull image

### ISSUE THREAD

**Issue by justincnn** [lan-tianxiang/jd_shell#5]
提示错误如下：
docker: Error response from daemon: pull access denied for lan-tianxiang/jd_shell, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by lan-tianxiang** [comment]
DockerHub上面我还没有上传映像，暂时只能用Dockerfile生成

**Comment by lan-tianxiang** [comment]
可以了，直接运行一键安装脚本即可，久等了😂
