### ISSUE TITLE
屏蔽某个账号不玩某些小游戏

### ISSUE THREAD

**Issue by 648839699** [lan-tianxiang/jd_shell#50]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：屏蔽某个账号不玩某些小游戏，这样设置是否正确，这样设置后不生效呢

## 如果只是想要屏蔽某个账号不玩某些小游戏，可以参考下面 case 这个命令的例子来控制，脚本名称请去掉后缀 “.js”
case $1 in
   jd_dreamFactory | jd_jxnc)
     TempBlockCookie="5"      # 账号5不玩京喜工厂、京喜农场、东东农场
     ;;
   jd_beauty)
     TempBlockCookie="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21"    # 不玩美丽研究院
     ;;
 jd_daily_egg)
     TempBlockCookie="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21"    # 不玩天天提鹅
     ;;
  esac

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
前面已经回复你了，是因为开启了自动助力，没有清楚缓存的原因。不过这个也算一个缺陷，我尽快改善，好吗😂&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："648839699 ***@***.***&gt;;
发送时间：2021年4月4日(星期天) 上午7:32
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 屏蔽某个账号不玩某些小游戏 (#50)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：屏蔽某个账号不玩某些小游戏，这样设置是否正确，这样设置后不生效呢
 
如果只是想要屏蔽某个账号不玩某些小游戏，可以参考下面 case 这个命令的例子来控制，脚本名称请去掉后缀 “.js”
 
case $1 in
 jd_dreamFactory | jd_jxnc)
 TempBlockCookie="5"      # 账号5不玩京喜工厂、京喜农场、东东农场
 ;;
 jd_beauty)
 TempBlockCookie="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21"    # 不玩美丽研究院
 ;;
 jd_daily_egg)
 TempBlockCookie="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21"    # 不玩天天提鹅
 ;;
 esac
 
(2) 详细日志
 
A：
