### ISSUE TITLE
用debian本地虚拟机安装出现依赖不安装不完整

### ISSUE THREAD

**Issue by agate520** [lan-tianxiang/jd_shell#53]
![photo_2021-04-04_11-58-55](https://user-images.githubusercontent.com/52735902/113498233-b9f02980-953d-11eb-8bbc-1206c2c0ed37.jpg)

**Comment by lan-tianxiang** [comment]
好的，你加群，我私下帮你看看

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："agate520 ***@***.***&gt;;
发送时间：2021年4月4日(星期天) 中午12:03
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 用debian本地虚拟机安装出现依赖不安装不完整 (#53)
-----------------------------------

**Comment by agate520** [comment]
你的群是多少啊

**Comment by agate520** [comment]
大佬你的群是多少给个链接呢

**Comment by lan-tianxiang** [comment]
967451175
