### ISSUE TITLE
jd_crazy_joy_coin

### ISSUE THREAD

**Issue by ryan016** [lan-tianxiang/jd_shell#55]
/jd/scripts/docker/crontab_list.sh
里面没有jd_crazy_joy_coin的内容
难怪这两天都没跑这个“挂机领金币/宝箱专用”脚本

**Comment by ryan016** [comment]
一键安装脚本拉取的脚本是包含了jd_crazy_joy_coin.js的，但配置里没有相关内容，所以配置面板定时任务里并没显示该脚本。

**Comment by baiye233** [comment]
bash jd.sh hangup这个挂机命令就可以了

**Comment by ryan016** [comment]
> bash jd.sh hangup这个挂机命令就可以了

多谢告知！！
