### ISSUE TITLE
jd.sh 语法错误：文件意外结束

### ISSUE THREAD

**Issue by ryan016** [lan-tianxiang/jd_shell#59]
`//jd/jd.sh: line 454: syntax error: unexpected end of file`

跑着跑着就出现这个提示了
手动执行任何脚本都是这个提示

**Comment by bymao** [comment]
我也遇到这个错误了。倒数第二行。新建一行
加个 esac。

**Comment by lan-tianxiang** [comment]
失誤啊，抱歉，已經修復了

**Comment by lan-tianxiang** [comment]
已經修復，抱歉，低級失誤
