### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by hacken156026692** [lan-tianxiang/jd_shell#6]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：安卓，termux

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：无法运行

### (2) 详细日志
A：
错误如下

bash git_pull.sh                                    grep: /data/data/com.termux/files/home/jd/.git/config: No such file or directory                                        grep: /data/data/com.termux/files/home/jd/scripts/.git/config: No such file or directory                                                                                            --------------------------------------------------------------                                                                                                                      系统时间：2021-02-21 16:59:57                                                                                           SHELL脚本目录：/data/data/com.termux/files/home/jd                                                                      JS脚本目录：/data/data/com.termux/files/home/jd/scripts                                                                 --------------------------------------------------------------                                                                                                                      更新shell脚本，原地址：https://github.com/lan-tianxiang/jd_shell                                                                                                                    fatal: not a git repository (or any parent up to mount point /)                                                         Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).                                              fatal: not a git repository (or any parent up to mount point /)                                                         Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).                                                                                                          shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...                                                                                        js脚本更新完成...

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by hacken156026692** [comment]
上面选错了，应该是安卓平台。

**Comment by lan-tianxiang** [comment]
有没有按步骤来呢，看这个日记是到运行git_pull.sh出现的错误。说明下第几步出现的错误，然后最好发截图来看看

**Comment by lan-tianxiang** [comment]
安装完依赖之后，克隆脚本，复制完配置文件之后呢，最后运行git_pull.sh

**Comment by lan-tianxiang** [comment]
刚刚在手机上重头走了一遍，没问题，你看下有没有遗漏什么步骤

**Comment by hacken156026692** [comment]
大神，您好。简单说一下过程：
1、把文件解压缩到termux的默认路径，~/jd文件夹里
2、新建config文件，把config和termux这两个的sample文件，复制到config文件夹里，去掉sample，重命名为crontab
3、把~/jd文件夹里的权限改成777
4、运行bash git_pull.sh，提示出错
5、再把以前别的人的脚本里的scripts文件夹拷过来
6、再次运行bash git_pull.sh，还是出错，同时自动把我scripts文件夹删掉了。

大致就这么个过程。烦请看看哪里出错了，谢谢！

**Comment by lan-tianxiang** [comment]
我看了一下，你这个解压缩是指的运行了这个命令吗？
`git clone https://github.com/lan-tianxiang/jd_shell jd`
这个项目不用用到解压缩这一步。还有个就是，一般情况下，权限只要chmod +x就可以了，没有必要777
感觉不懂的话，你发QQ，我可以具体看看

**Comment by hacken156026692** [comment]
我是直接网页上下载了压缩包，然后在mt文件管理器里解压缩到左边的~/jd文件夹，一开始运行时提示pemission denied，所以设置了777。我再用clone的试一下先。

**Comment by lan-tianxiang** [comment]
> 我是直接网页上下载了压缩包，然后在mt文件管理器里解压缩到左边的~/jd文件夹，一开始运行时提示pemission denied，所以设置了777。我再用clone的试一下先。


哈哈，我就说嘛。按步骤走吧。还有就是，MT管理器很多命令不支持，去软件商城下载termux运行命令就行

**Comment by lan-tianxiang** [comment]
软件商城没有的话，就下载酷安，或者百度一搜也能搜到

**Comment by lan-tianxiang** [comment]
termux用的不习惯，可以用mt修改参数,但是命令必须得用Termux

**Comment by hacken156026692** [comment]
行了，谢谢大神。终于成功了。少走不少弯路。您QQ号或电报号是多少？以后可以及时看您动态或咨询您^_^

**Comment by lan-tianxiang** [comment]
哈哈，可以了就好。就不发联系方式了。撸豆愉快！

**Comment by hacken156026692** [comment]
不好意思。临时自说自话又打开评论，还想问一下，我运行bash git_pull.sh，提示如下

更新shell脚本，原地址：https://github.com/lan-tianxiang/jd_shell

Fetching origin
HEAD is now at 763c3a7 暂时修复完成！！！！
Can't do inplace edit on /data/data/com.termux/files/home/jd/config/crontab.list: Cannot make temp name: Permission denied.
Can't do inplace edit on /data/data/com.termux/files/home/jd/config/crontab.list: Cannot make temp name: Permission denied.

shell脚本更新完成...

我crontab文件已经设置777，或设置chomd ，为何还是denied？谢谢。
