### ISSUE TITLE
大佬,安卓能可视化吗,顺便求一下安卓的ip+端口

### ISSUE THREAD

**Issue by lys01** [lan-tianxiang/jd_shell#60]
rt

**Comment by lan-tianxiang** [comment]
安卓也是一样的，运行完面板程序以后，打开浏览器输入127.0.0.1:5678就进入了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："lys66666 ***@***.***&gt;;
发送时间：2021年4月6日(星期二) 晚上7:43
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 大佬,安卓能可视化吗,顺便求一下安卓的ip+端口 (#60)
-----------------------------------

 

 
rt
