### ISSUE TITLE
我发现自助填写助力码，有些活动还是没有助力成功，比如惊喜农场

### ISSUE THREAD

**Issue by Juice-9** [lan-tianxiang/jd_shell#65]
`##<!--`
反馈前请阅读

- 常见问题： https://github.com/lan-tianxiang/jd_shell/wiki/FAQ
- 使用教程： https://github.com/lan-tianxiang/jd_shell/wiki/Documents
- 请先在 issues 页面搜索你的问题，包括已关闭的issue，很可能已被解决。
-->

## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by ryan016** [comment]
`ForOtherJxnc1='{"smp"……m":3}@{"smp":……","jm":2}@{"smp":"……um":2}'`
助力码每重新生产会变换

**Comment by lan-tianxiang** [comment]
惊喜农场比较特殊，特别是第一次种植选择特有的水果的时候，要按照格式填写
