### ISSUE TITLE
运行bash jd.sh panelon 开启面板后  就可以放着不管了吗?

### ISSUE THREAD

**Issue by yu1chaofan** [lan-tianxiang/jd_shell#67]
Cookie 已经配置好了  只需要开启面板就可以不用管了吗?

**Comment by lan-tianxiang** [comment]
对，是的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yu1chaofan ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 凌晨2:23
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 运行bash jd.sh panelon 开启面板后  就可以放着不管了吗? (#67)
-----------------------------------

 

 
Cookie 已经配置好了  只需要开启面板就可以不用管了吗?

**Comment by 442774765** [comment]
是这样子的。AutoHelpme改了true.我没自己添加辅助码，然后运行的时候日志显示获起20个互助码不影响固定互助码，然后开始助力的时候，他直接助力20个互助码，按顺序排队助力。没有内部助力4G账号。所以我想问的是，是不是还得要自己添加互助码才行。

**Comment by lan-tianxiang** [comment]
不是这样的，会自动添加，不过你所有的活动要先运行过一遍，才会获取助力码

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："442774765 ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 上午8:48
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 运行bash jd.sh panelon 开启面板后  就可以放着不管了吗? (#67)
-----------------------------------

 

 
是这样子的。AutoHelpme改了true.我没自己添加辅助码，然后运行的时候日志显示获起20个互助码不影响固定互助码，然后开始助力的时候，他直接助力20个互助码，按顺序排队助力。没有内部助力4G账号。所以我想问的是，是不是还得要自己添加互助码才行。

**Comment by lan-tianxiang** [comment]
你的那个脚本单独先运行一次，再运行的时候就会有了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："442774765 ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 上午8:48
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 运行bash jd.sh panelon 开启面板后  就可以放着不管了吗? (#67)
-----------------------------------

 

 
是这样子的。AutoHelpme改了true.我没自己添加辅助码，然后运行的时候日志显示获起20个互助码不影响固定互助码，然后开始助力的时候，他直接助力20个互助码，按顺序排队助力。没有内部助力4G账号。所以我想问的是，是不是还得要自己添加互助码才行。
