### ISSUE TITLE
可视化面板开启不了

### ISSUE THREAD

**Issue by sudolxwh** [lan-tianxiang/jd_shell#68]

**Comment by rometuo** [comment]
一样

**Comment by rometuo** [comment]
> 我也一样的问题 在百度后
更新环境就可以了帖子在下面
https://blog.csdn.net/u012313361/article/details/107480635

**Comment by gitxss** [comment]
> > 我也一样的问题 在百度后
> > 更新环境就可以了帖子在下面
> > https://blog.csdn.net/u012313361/article/details/107480635

谢谢兄弟

**Comment by lan-tianxiang** [comment]
> > 我也一样的问题 在百度后
> > 更新环境就可以了帖子在下面
> > https://blog.csdn.net/u012313361/article/details/107480635

强！ 的确多数人都是这个原因。

**Comment by lan-tianxiang** [comment]
此版本JD_SHELL正式停止更新，新版本请查看 https://github.com/lan-tianxiang/js_tool ！
