### ISSUE TITLE
https://gitee.com/lxk0301/jd_scripts 被私有化，无法完成 dock 的创建

### ISSUE THREAD

**Issue by cnkmmk** [lan-tianxiang/jd_shell#7]
如题

后期脚本会逐步进行加密后发布(原因:部分人偷盗脚本,然后进行改脚本内置邀请码后再次宣传修改后的)
2021.02.21日，jd_scripts仓库被迫私有 详见一，详见二，最新镜像 (国内其他什么阿里云的源以及网易云的源目前都不是最新的)

**Comment by lan-tianxiang** [comment]
好的，感谢告知。
