### ISSUE TITLE
任务并发问题

### ISSUE THREAD

**Issue by leifengwl** [lan-tianxiang/jd_shell#70]
我看首页说已经有了多账户并发执行任务功能，但我在配置里没有找到，也测试了一些任务  比如东东农场 ，它还是按顺序执行的，等前面完成了 后面的才执行，是我没开启吗？

**Comment by lan-tianxiang** [comment]
此版本JD_SHELL正式停止更新，新版本请查看 https://github.com/lan-tianxiang/js_tool ！

里面有多任务并发功能
