### ISSUE TITLE
无法执行git_pull.sh和cd ~/jd/scripts

### ISSUE THREAD

**Issue by dayvight** [lan-tianxiang/jd_shell#8]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Android 11 Termux 0.101

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：无法执行git_pull.sh和cd ~/jd/scripts

### (2) 详细日志
A：cd ~/jd
      chmod +x *.sh
      bash git_pull.sh
grep: /data/data/com.termux/files/home/jd/scripts/.git/config: Not a directory
Start

--------------------------------------------------------------

系统时间：2021-02-26 23:43:44

SHELL脚本目录：/data/data/com.termux/files/home/jd

JS脚本目录：/data/data/com.termux/files/home/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://github.com/lan-tianxiang/jd_shell

Fetching origin
warning: redirecting to https://github.com/lan-tianxiang/jd_shell/
HEAD is now at bbed3a5 Update README.md
git_pull.sh: line 73: perl: command not found
git_pull.sh: line 74: perl: command not found
git_pull.sh: line 75: crontab: command not found
git_pull.sh: line 358: perl: command not found
git_pull.sh: line 359: perl: command not found

shell脚本更新完成...

--------------------------------------------------------------

克隆LXK9301脚本，原地址：https://github.com/RikudouPatrickstar/jd_scripts

fatal: destination path '/data/data/com.termux/files/home/jd/scripts' already exists and is not an empty directory.

更新shylocks脚本，原地址：https://github.com/lan-tianxiang/jd_scripts

Fetching origin
HEAD is now at 191e39e add

js脚本更新失败，请检查原因或再次运行git_pull.sh...

git_pull.sh: line 135: perl: command not found
printf: usage: printf [-v var] format [arguments]
git_pull.sh: line 142: perl: command not found

cd ~/jd/scripts
cd: not a directory: /data/data/com.termux/files/home/jd/scripts

**Comment by lan-tianxiang** [comment]
perl没有安装。&nbsp; &nbsp;看termux的第一步，安装依赖哪里，你有可能网络不好没有安装完整，重新运行那一步


----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："dayvight "<notifications@github.com&gt;;
发送时间：2021年2月26日(星期五) 晚上11:47
收件人："lan-tianxiang/jd_shell" <jd_shell@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[lan-tianxiang/jd_shell] 无法执行git_pull.sh和cd ~/jd/scripts (#8)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
[x ] 没有类似的issue 
  
Q：是否阅读了常见问题
  
[ x] 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
[ x] 已仔细阅读教程 
  
2. 使用什么平台，精确到版本
 
A：Android 11 Termux 0.101
 
3. 按照以下哪个教程做的
  
 Linux
 
[x ] Android
 
 MacOS
 
 Docker
  
4. 详细叙述
 
(1) 具体问题
 
A：无法执行git_pull.sh和cd ~/jd/scripts
 
(2) 详细日志
 
A：cd ~/jd
 chmod +x *.sh
 bash git_pull.sh
 grep: /data/data/com.termux/files/home/jd/scripts/.git/config: Not a directory
 Start
 
 
系统时间：2021-02-26 23:43:44
 
SHELL脚本目录：/data/data/com.termux/files/home/jd
 
JS脚本目录：/data/data/com.termux/files/home/jd/scripts
 
 
更新shell脚本，原地址：https://github.com/lan-tianxiang/jd_shell
 
Fetching origin
 warning: redirecting to https://github.com/lan-tianxiang/jd_shell/
 HEAD is now at bbed3a5 Update README.md
 git_pull.sh: line 73: perl: command not found
 git_pull.sh: line 74: perl: command not found
 git_pull.sh: line 75: crontab: command not found
 git_pull.sh: line 358: perl: command not found
 git_pull.sh: line 359: perl: command not found
 
shell脚本更新完成...
 
 
克隆LXK9301脚本，原地址：https://github.com/RikudouPatrickstar/jd_scripts
 
fatal: destination path '/data/data/com.termux/files/home/jd/scripts' already exists and is not an empty directory.
 
更新shylocks脚本，原地址：https://github.com/lan-tianxiang/jd_scripts
 
Fetching origin
 HEAD is now at 191e39e add
 
js脚本更新失败，请检查原因或再次运行git_pull.sh...
 
git_pull.sh: line 135: perl: command not found
 printf: usage: printf [-v var] format [arguments]
 git_pull.sh: line 142: perl: command not found
 
cd ~/jd/scripts
 cd: not a directory: /data/data/com.termux/files/home/jd/scripts

**Comment by dayvight** [comment]
这个问题解决了，jd/scripts已存在，删除后就可以运行了。请问一下，运行jd.sh之后，可运行的脚本需要一个个运行吗？

**Comment by lan-tianxiang** [comment]
不用，会自动运行。 不过用termux或者是Windows 的wls安装的ubantu需要多一步，启动cron服务。


不过你可以手动运行一个脚本看一下是否正常

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："dayvight "<notifications@github.com&gt;;
发送时间：2021年2月27日(星期六) 晚上11:41
收件人："lan-tianxiang/jd_shell" <jd_shell@noreply.github.com&gt;;
抄送："lan-tianxiang "<admin@highdimen.com&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [lan-tianxiang/jd_shell] 无法执行git_pull.sh和cd ~/jd/scripts (#8)
-----------------------------------

 

 
这个问题解决了，jd/scripts已存在，删除后就可以运行了。请问一下，运行jd.sh之后，可运行的脚本需要一个个运行吗？

**Comment by dayvight** [comment]
脚本能够正常运行，请问该如何使用可视化操作面板呢？我无法进入主目录
cd /home/myid/jd
cd; no such file or directory; /home/myid/jd

**Comment by lan-tianxiang** [comment]
cd ~/jd/scripts
bash jd.sh panelinit
就可以了，连上局域网wifi还可以用电脑访问

**Comment by dayvight** [comment]
cd  ~/jd/scripts
bash jd.sh panelinit
bash: jd.sh: No such file or directory
这个样子还是不可以，求解

**Comment by lan-tianxiang** [comment]
cd ~/jd
bash jd.sh panelinit
就可以了，同意局域网都可以访问
----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："dayvight ***@***.***&gt;;
发送时间：2021年3月17日(星期三) 晚上11:50
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 无法执行git_pull.sh和cd ~/jd/scripts (#8)
-----------------------------------

 

 
cd  ~/jd/scripts
 bash jd.sh panelinit
 bash: jd.sh: No such file or directory
 这个样子还是不可以，求解
