### ISSUE TITLE
可以出一个docker2吗？

### ISSUE THREAD

**Issue by Lehcok** [lan-tianxiang/jd_shell#9]
希望大佬可以出一个docker2的教程，跪谢了

**Comment by lan-tianxiang** [comment]
下周前出

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："a370263995 ***@***.***&gt;;
发送时间：2021年3月12日(星期五) 下午4:34
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 可以出一个docker2吗？ (#9)
-----------------------------------

 

 
希望大佬可以出一个docker2的教程，跪谢了

**Comment by lan-tianxiang** [comment]
可以了，直接运行一键安装脚本即可，久等了😂
