### ISSUE TITLE
可视化网站突然打不开了

### ISSUE THREAD

**Issue by tomlongcool** [lan-tianxiang/jd_shell#90]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x ] No

### (1) 具体问题
A：昨天还是可以打开面板网站的，今天突然就打不开网站了报503错误，重启了面板还是不行。重启了服务器还是不行

### (2) 详细日志
A：

**Comment by huanghuixin1** [comment]
我也是 今天出现的

**Comment by tomlongcool** [comment]
> 我也是 今天出现的

我重装系统 然后重新装了一边 现在好了 - = -

**Comment by lan-tianxiang** [comment]
是面板更新了，同步a1版本的界面和功能

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tomlongcool ***@***.***&gt;;
发送时间：2021年5月30日(星期天) 下午4:37
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90)
-----------------------------------

 

  
我也是 今天出现的
  
我重装系统 然后重新装了一边 现在好了 - = -

**Comment by zdmisif** [comment]
我也是打不开了，请问怎么处理？

**Comment by tomlongcool** [comment]
> 是面板更新了，同步a1版本的界面和功能
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tomlongcool ***@***.***&gt;; 发送时间：2021年5月30日(星期天) 下午4:37 收件人："lan-tianxiang/jd_shell" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90) ----------------------------------- 我也是 今天出现的 我重装系统 然后重新装了一边 现在好了 - = - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ok，谢谢大佬-

**Comment by zdmisif** [comment]
> > 是面板更新了，同步a1版本的界面和功能
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："tomlongcool _**@**_._**>; 发送时间：2021年5月30日(星期天) 下午4:37 收件人："lan-tianxiang/jd_shell" _**@**_.**_>; 抄送："Subscribed _**@**_.***>; 主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90) ----------------------------------- 我也是 今天出现的 我重装系统 然后重新装了一边 现在好了 - = - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ok，谢谢大佬-

请问是怎么解决的呢？

**Comment by zdmisif** [comment]
> 是面板更新了，同步a1版本的界面和功能
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tomlongcool ***@***.***&gt;; 发送时间：2021年5月30日(星期天) 下午4:37 收件人："lan-tianxiang/jd_shell" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90) ----------------------------------- 我也是 今天出现的 我重装系统 然后重新装了一边 现在好了 - = - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，求解决的办法哇

**Comment by lan-tianxiang** [comment]
> > 是面板更新了，同步a1版本的界面和功能
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："tomlongcool _**@**_._**>; 发送时间：2021年5月30日(星期天) 下午4:37 收件人："lan-tianxiang/jd_shell" _**@**_.**_>; 抄送："Subscribed _**@**_.***>; 主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90) ----------------------------------- 我也是 今天出现的 我重装系统 然后重新装了一边 现在好了 - = - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 大佬，求解决的办法哇

@zdmisif   
方法一：可以复制一下你数据，然后重新部署
方法二：
```
cd jd/panel
yarn
```

**Comment by zdmisif** [comment]
> > > 是面板更新了，同步a1版本的界面和功能
> > > […](#)
> > > ---------- 该邮件从移动设备发送
> > > --------------原始邮件-------------- 发件人："tomlongcool _**@**_._**>; 发送时间：2021年5月30日(星期天) 下午4:37 收件人："lan-tianxiang/jd_shell" _**@**_.**_>; 抄送："Subscribed _**@**_.***>; 主题：Re: [lan-tianxiang/jd_shell] 可视化网站突然打不开了 (#90) ----------------------------------- 我也是 今天出现的 我重装系统 然后重新装了一边 现在好了 - = - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 大佬，求解决的办法哇
> 
> @zdmisif
> 方法一：可以复制一下你数据，然后重新部署
> 方法二：
> 
> ```
> cd jd/panel
> yarn
> ```

收到
