### ISSUE TITLE
我搭建在云服务器上，该如何使用呢？

### ISSUE THREAD

**Issue by ziluxike** [lan-tianxiang/jd_shell#93]
访问地址是127.0.0.1:5678，是可以使用端口映射出去吗？

**Comment by Mashiro2000** [comment]
开放5678端口

**Comment by lan-tianxiang** [comment]
> 访问地址是127.0.0.1:5678，是可以使用端口映射出去吗？

云服务器的话，只要阿里云或者腾讯云上的防火墙，就可以访问了，不用映射

**Comment by ziluxike** [comment]
> > 访问是127.0.0.1:5678，是可以使用地址映射出去吗？
> 
> 云服务器的话，只要阿里云或者腾讯云上的防火墙，就可以访问了，不用映射

好的
