### ISSUE TITLE
关于挂机问题

### ISSUE THREAD

**Issue by Mashiro2000** [lan-tianxiang/jd_shell#94]
今天刚刚发现这个脚本，购买了服务器，Linux暂时还没学习，不懂，我想要挂后台，使用了以下两个命令，是否正确？
还有就是【定时设定】这个功能具体是什么，还需要我们手动执行吗，还是系统自动调用执行？
nohup sh jd.sh & 
nohup sh run_all.sh &

**Comment by lan-tianxiang** [comment]
不用的，只要安装完成后，配置好账号，就会自动后台运行的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Mashiro2000 ***@***.***&gt;;
发送时间：2021年5月31日(星期一) 凌晨1:06
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 关于挂机问题 (#94)
-----------------------------------

 

 
今天刚刚发现这个脚本，购买了服务器，Linux暂时还没学习，不懂，我想要挂后台，使用了以下两个命令，是否正确？
 还有就是【定时设定】这个功能具体是什么，还需要我们手动执行吗，还是系统自动调用执行？
 nohup sh jd.sh &amp;
 nohup sh run_all.sh &amp;

**Comment by lan-tianxiang** [comment]
系统会自动调用，只需打开面板配置账号即可

**Comment by Mashiro2000** [comment]
您好，我想要的效果是，在服务器上运行，后台挂脚本，
但是，我一旦断开终端连接，好像就不运行了
想要达到以上效果，请问是只需要执行以下哪个命令，
run_all.sh
bash jd.sh hangup

**Comment by lan-tianxiang** [comment]
> 您好，我想要的效果是，在服务器上运行，后台挂脚本，
> 但是，我一旦断开终端连接，好像就不运行了
> 想要达到以上效果，请问是只需要执行以下哪个命令，
> run_all.sh
> bash jd.sh hangup

```
 但是，我一旦断开终端连接，好像就不运行了
```

断开终端不会影响自动运行定时任务的，不太懂的话，可以帮你部署

```
run_all.sh
```
这个是运行一遍全部的任务

```
bash jd.sh hangup
```
这个是joy收集金币的任务

**Comment by Mashiro2000** [comment]
请问如何跟你联系，我把服务器信息给你

**Comment by Mashiro2000** [comment]
如果不方便透露你的联系方式，我提供我的联系方式，QQ2984922017
微信f2984922017

**Comment by lan-tianxiang** [comment]
好的

**Comment by kotonamihuiren** [comment]
你好，如何循环run_all.sh 里的所有命令每天循环     每次都是脚本跑完自动进入joy收金币 每天还要进服务器里面重新输入run_all.sh

**Comment by lan-tianxiang** [comment]
不用，都会自动运行，不用进服务器，配置好账号即可

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："kotonamihuiren ***@***.***&gt;;
发送时间：2021年5月31日(星期一) 下午5:19
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 关于挂机问题 (#94)
-----------------------------------

 

 
你好，如何循环run_all.sh 里的所有命令每天循环     每次都是脚本跑完自动进入joy收金币 每天还要进服务器里面重新输入run_all.sh
