### ISSUE TITLE
请问这是执行成功的日志吗？

### ISSUE THREAD

**Issue by PS0123456** [lan-tianxiang/jd_shell#98]
root@jd:~/jd $ bash jd.sh jd_zooCollect.js
0000

命令未添加 "now"，随机延迟 5 秒后再执行任务，如需立即终止，请按 CTRL+C...

🔔618动物联萌收集金币, 开始!

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/2下午7:47:35=====================

您的操作系统为：UnKnow 架构：x86_64

但实际进入APP没发现有收集啊？

Docker

**Comment by PS0123456** [comment]
所有任务日志都这样，没详细的

**Comment by PS0123456** [comment]
目前发现所有脚本执行之后都出现“卡机”情况，后续无执行

**Comment by lan-tianxiang** [comment]
是不是使用了并发运行全部任务的命令呢，这条命令的确比较的...危险😨&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："PS0123456 ***@***.***&gt;;
发送时间：2021年6月2日(星期三) 晚上9:39
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 请问这是执行成功的日志吗？ (#98)
-----------------------------------

 

 
目前发现所有脚本执行之后都出现“卡机”情况，后续无执行

**Comment by PS0123456** [comment]
不，并没有，我反复尝试重启后台挂机任务，docker 重启JD，结局一样，考虑Bug？

**Comment by PS0123456** [comment]
目前少数插件可以运行，但比如618宠物联盟依然不行🙅

**Comment by lan-tianxiang** [comment]
@PS0123456  618更新一下就可以了

**Comment by lan-tianxiang** [comment]
618宠物联盟和金币收集 10点修复的

**Comment by qingcheng123** [comment]
centos下出现这个怎么解决
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
您的操作系统为：Centos 架构：x86_64

**Comment by lan-tianxiang** [comment]
@qingcheng123   centos 的 nodejs版本问题，百度搜索`node升级`

**Comment by lan-tianxiang** [comment]
@qingcheng123  或者安装docker,然后用docker的安装脚本

**Comment by qingcheng123** [comment]
好的，谢谢，我试试 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月3日(星期四) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 请问这是执行成功的日志吗？ (#98)

**Comment by PS0123456** [comment]
> 618宠物联盟和金币收集 10点修复的
金币的确可以收集了，但宠物联盟没效果，包括浏览加购商品， 逛店 ，逛会场。

操作记录：
docker exec -it jd /bin/bash
bash jd.sh update
bash jd.sh jd_zoo.js

🔔618动物联萌, 开始!

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/3下午7:43:31=====================

您的操作系统为：UnKnow 架构：x86_64

...

**Comment by PS0123456** [comment]
再次手动执行，成功，上面可能是抽风？
